DOMAIN = "vbb_routes_location_button"

CONF_ORIGIN_ENTITY = "origin_entity"
CONF_NOTIFY_SERVICE = "notify_service"
CONF_LOCATION_UPDATE_WAIT_SECONDS = "location_update_wait_seconds"
CONF_DESTINATION_ID = "destination_id"
CONF_DESTINATION_NAME = "destination_name"
CONF_DESTINATION_ADDRESS = "destination_address"
CONF_DESTINATION_LAT = "destination_lat"
CONF_DESTINATION_LON = "destination_lon"
CONF_MIN_DEPART_OFFSET_MIN = "min_depart_offset_min"
CONF_MAX_TRANSFERS = "max_transfers"
CONF_RESULTS = "results"
CONF_TOP_N = "top_n"

DEFAULT_NAME = "VBB Alisa Location"
DEFAULT_ORIGIN_ENTITY = "device_tracker.alisa_phone"
DEFAULT_NOTIFY_SERVICE = ""
DEFAULT_LOCATION_UPDATE_WAIT_SECONDS = 7
DEFAULT_DESTINATION_ID = "900130002"
DEFAULT_DESTINATION_NAME = "S+U Pankow"
DEFAULT_DESTINATION_ADDRESS = "Karl-Marx-Allee 72, 10243 Berlin"
DEFAULT_DESTINATION_LAT = 52.517481
DEFAULT_DESTINATION_LON = 13.436806
DEFAULT_MIN_DEPART_OFFSET_MIN = 7
DEFAULT_MAX_TRANSFERS = 1
DEFAULT_RESULTS = 20
DEFAULT_TOP_N = 3

VBB_JOURNEYS_URL = "https://v6.vbb.transport.rest/journeys"
